# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Default
version:      1.0
version_from: lib/Class/Default.pm
installdirs:  site
requires:
    Class::Inspector:              1
    File::Spec:                    0.83
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
