abstract: Static calls apply to a default instantiation
author: Adam Kennedy <cpan@ali.as>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Class-Default
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.005
version: 1.50
