name: Class-Default
version: 1.1
abstract: Static methods apply to a default instantiation
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
