
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.57
distribution_type: module
version: 1.4
name: Class-Default
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.82
requires: 
  perl: 5.005
abstract: Static calls apply to a default instantiation
